language: objective-c
osx_image: xcode11.5
script:
  - set -o pipefail
  - xcodebuild -workspace ESPProvision.xcworkspace -scheme ESPProvision build | xcpretty
before_install:
  - gem install cocoapods
  - pod install
after_success:
  - gem install jazzy
  - make documentation
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: docs
  on:
    branch: master